all:

install:
	install -D phomemo-filter-m02.py -t $(DESTDIR)/usr/share/phomemo/
	install -D phomemo-filter-m02s.py -t $(DESTDIR)/usr/share/phomemo/
	install -D format-checker.py -t $(DESTDIR)/usr/share/phomemo/
